events {}

http {
    server {
        listen 80;
        server_name _;

        # -----------------------
        # FRONTEND (ROOT PATH)
        # -----------------------
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
        }

        # -----------------------
        # ADMIN PANEL
        # -----------------------
        location /admin/ {
            proxy_pass http://admin:80/;
            proxy_set_header Host $host;
        }

        # -----------------------
        # BACKEND API
        # -----------------------
        location /api {
            proxy_pass http://backend:4000;
            proxy_set_header Host $host;
        }
    }
}
